import { Palette } from "./colors";
import type {
	AppearanceContent,
	HighlightStyleContent,
	ThemeContent,
	ThemeStyleContent,
} from "./types";

export function createTheme(
	name: string,
	appearance: AppearanceContent,
	palette: Palette,
): ThemeContent {
	return {
		name: `The ${name} Tone`,
		appearance: appearance,
		style: createStyle(appearance, palette),
	};
}

export const createStyle = (appearance: AppearanceContent, palette: Palette): ThemeStyleContent => {
	const isDark = appearance === "dark";
	const color = colorGetter(isDark, palette);
	return {
		"accents": [color("cyan"), color("green"), color("orange"), color("magenta"), color("yellow")],
		"background.appearance": "opaque",
		"border": color("border"),
		"border.variant": color("border"),
		"border.focused": color("border"),
		"border.selected": color("border"),
		"border.transparent": color("border"),
		"border.disabled": color("border"),
		"elevated_surface.background": color("background"),
		"surface.background": color("background"),
		"background": color("background"),
		"element.background": color("activeBackground"),
		"element.hover": color("faded"),
		"element.active": color("selectionBackgroundInActive"),
		"element.selected": color("selectionBackgroundInActive"),
		"element.disabled": color("background"),
		"element.selection_background": color("foreground", "semi-transparent"),
		"drop_target.background": color("selectionBackgroundInActive"),
		"drop_target.border": color("primary"),
		"ghost_element.background": null,
		"ghost_element.hover": color("faded"),
		"ghost_element.active": color("selectionBackgroundInActive"),
		"ghost_element.selected": color("selectionBackgroundInActive"),
		"ghost_element.disabled": color("background"),
		"text": color("foreground"),
		"text.muted": color("secondaryForeground"),
		"text.placeholder": color("ignored"),
		"text.disabled": color("ignored"),
		"text.accent": color("primary"),
		"icon": color("foreground"),
		"icon.muted": color("secondaryForeground"),
		"icon.disabled": color("ignored"),
		"icon.placeholder": color("ignored"),
		"icon.accent": color("primary"),
		"status_bar.background": color("background"),
		"title_bar.background": color("background"),
		"title_bar.inactive_background": color("background"),
		"toolbar.background": color("activeBackground"),
		"tab_bar.background": color("background"),
		"tab.inactive_background": color("background"),
		"tab.active_background": color("activeBackground"),
		"search.match_background": color("activeBackground"),
		"panel.background": color("background"),
		"panel.focused_border": color("ignored"),
		"panel.indent_guide": color("activeBackground"),
		"panel.indent_guide_active": color("selectionBackground"),
		"panel.indent_guide_hover": color("selectionBackground"),
		"panel.overlay_background": color("background"),
		"panel.overlay_hover": color("activeBackground"),
		"pane.focused_border": color("border"),
		"pane_group.border": color("border"),

		"scrollbar.thumb.background": color("selectionBackground"),
		"scrollbar.thumb.hover_background": color("selectionBackgroundActive"),
		"scrollbar.thumb.active_background": color("selectionBackgroundInActive"),
		"scrollbar.thumb.border": color("border"),
		"scrollbar.track.background": color("background"),
		"scrollbar.track.border": color("border"),
		"minimap.thumb.background": color("selectionBackground"),
		"minimap.thumb.hover_background": color("selectionBackgroundActive"),
		"minimap.thumb.active_background": color("selectionBackgroundInActive"),
		"minimap.thumb.border": color("border"),

		"editor.foreground": color("foreground"),
		"editor.background": color("background"),
		"editor.gutter.background": color("background"),
		"editor.subheader.background": color("background"),
		"editor.active_line.background": color("activeBackground"),
		"editor.highlighted_line.background": color("background"),
		"editor.line_number": color("ignored"),
		"editor.active_line_number": color("activeForeground"),
		"editor.hover_line_number": color("activeForeground"),
		"editor.invisible": color("selectionBackground"),
		"editor.wrap_guide": color("selectionBackground"),
		"editor.active_wrap_guide": color("selectionBackground"),
		"editor.document_highlight.read_background": color("activeBackground"),
		"editor.document_highlight.write_background": color("activeBackground"),
		"editor.document_highlight.bracket_background": color("selectionBackground"),
		"editor.indent_guide": color("activeBackground"),
		"editor.indent_guide_active": color("selectionBackground"),
		"link_text.hover": color("blue"),
		"debugger.accent": color("red"),
		"editor.debugger_active_line.background": color("activeBackground"),

		"vim.mode.text": color("foreground"),
		"vim.normal.background": color("background"),
		"vim.helix_normal.background": color("background"),
		"vim.visual.background": color("background"),
		"vim.visual_line.background": color("background"),
		"vim.helix_select.background": color("background"),
		"vim.visual_block.background": color("background"),
		"vim.insert.background": color("background"),
		"vim.replace.background": color("background"),

		"terminal.background": color("background"),
		"terminal.foreground": color("foreground"),
		"terminal.bright_foreground": color("foreground"),
		"terminal.dim_foreground": color("foreground"),
		"terminal.ansi.background": color("background"),
		"terminal.ansi.black": isDark ? color("foreground") : color("background"),
		"terminal.ansi.bright_black": isDark ? "#777777" : "#aaaaaa",
		"terminal.ansi.dim_black": isDark ? "#777777" : "#aaaaaa",
		"terminal.ansi.red": color("red"),
		"terminal.ansi.bright_red": color("red"),
		"terminal.ansi.dim_red": color("red"),
		"terminal.ansi.green": color("green"),
		"terminal.ansi.bright_green": color("green"),
		"terminal.ansi.dim_green": color("green"),
		"terminal.ansi.yellow": color("yellow"),
		"terminal.ansi.bright_yellow": color("yellow"),
		"terminal.ansi.dim_yellow": color("yellow"),
		"terminal.ansi.blue": color("blue"),
		"terminal.ansi.bright_blue": color("blue"),
		"terminal.ansi.dim_blue": color("blue"),
		"terminal.ansi.magenta": color("magenta"),
		"terminal.ansi.bright_magenta": color("magenta"),
		"terminal.ansi.dim_magenta": color("magenta"),
		"terminal.ansi.cyan": color("cyan"),
		"terminal.ansi.bright_cyan": color("cyan"),
		"terminal.ansi.dim_cyan": color("cyan"),
		"terminal.ansi.white": "#dbd7ca",
		"terminal.ansi.bright_white": "#dbd7ca",
		"terminal.ansi.dim_white": "#dbd7ca",

		"conflict": color("orange"),
		"conflict.background": color("orange", "semi-transparent"),
		"conflict.border": color("orange"),
		"created": color("green"),
		"created.background": color("green", "semi-transparent"),
		"created.border": color("green"),
		"deleted": color("red"),
		"deleted.background": color("red", "semi-transparent"),
		"deleted.border": color("red"),
		"error": color("red"),
		"error.background": color("red", "semi-transparent"),
		"error.border": color("red"),
		"hidden": color("ignored"),
		"hidden.background": color("ignored", "semi-transparent"),
		"hidden.border": color("ignored"),
		"hint": color("punctuation"),
		"hint.background": color("blue", "semi-transparent"),
		"hint.border": color("blue"),
		"ignored": color("ignored"),
		"ignored.background": color("ignored", "semi-transparent"),
		"ignored.border": color("ignored"),
		"info": color("blue"),
		"info.background": color("selectionBackground"),
		"info.border": color("blue"),
		"modified": color("blue"),
		"modified.background": color("blue", "semi-transparent"),
		"modified.border": color("blue"),
		"predictive": color("punctuation"),
		"predictive.background": color("punctuation", "semi-transparent"),
		"predictive.border": color("punctuation"),
		"renamed": color("cyan"),
		"renamed.background": color("cyan", "semi-transparent"),
		"renamed.border": color("cyan"),
		"success": color("green"),
		"success.background": color("green", "semi-transparent"),
		"success.border": color("green"),
		"unreachable": color("ignored"),
		"unreachable.background": color("ignored", "semi-transparent"),
		"unreachable.border": color("ignored"),
		"version_control.added": color("green"),
		"version_control.modified": color("blue"),
		"version_control.deleted": color("red"),
		"version_control.renamed": color("yellow"),
		"version_control.conflict": color("orange"),
		"version_control.conflict_marker.ours": color("green", "semi-transparent"),
		"version_control.conflict_marker.theirs": color("blue", "semi-transparent"),
		"version_control.ignored": color("ignored"),
		warning: color("orange"),
		"warning.background": color("orange", "semi-transparent"),
		"warning.border": color("orange"),

		players: [
			{
				cursor: color("foreground"),
				background: color("foreground"),
				selection: isDark ? "#363636" : "#dcdbd6",
			},
			{
				cursor: color("orange"),
				background: color("orange"),
				selection: color("orange", "semi-transparent"),
			},
			{
				cursor: color("yellow"),
				background: color("yellow"),
				selection: color("yellow", "semi-transparent"),
			},
			{
				cursor: color("green"),
				background: color("green"),
				selection: color("green", "semi-transparent"),
			},
			{
				cursor: color("cyan"),
				background: color("cyan"),
				selection: color("cyan", "semi-transparent"),
			},
			{
				cursor: color("blue"),
				background: color("blue"),
				selection: color("blue", "semi-transparent"),
			},
			{
				cursor: color("magenta"),
				background: color("magenta"),
				selection: color("magenta", "semi-transparent"),
			},
			{
				cursor: color("red"),
				background: color("red"),
				selection: color("red", "semi-transparent"),
			},
		],

		syntax: {
			"attribute": syntax(color("variable")),
			"boolean": syntax(color("boolean")),
			"character": syntax(color("foreground")),
			"character.special": syntax(color("foreground")),
			"comment": syntax(color("comment")),
			"comment.doc": syntax(color("comment")),
			"comment.documentation": syntax(color("comment")),
			"comment.error": syntax(color("comment")),
			"comment.hint": syntax(color("comment")),
			"comment.note": syntax(color("comment")),
			"comment.todo": syntax(color("comment")),
			"comment.warning": syntax(color("comment")),
			"concept": syntax(color("foreground")),
			"constant": syntax(color("variable")),
			"constant.builtin": syntax(color("red")),
			"constant.macro": syntax(color("constant")),
			"constructor": syntax(color("keyword")),
			"diff": syntax(color("foreground")),
			"diff.minus": syntax(color("foreground")),
			"diff.plus": syntax(color("foreground")),
			"embedded": syntax(color("foreground")),
			"emphasis": syntax(color("foreground"), "italic"),
			"emphasis.strong": syntax(color("foreground"), "bold"),
			"enum": syntax(color("foreground")),
			"field": syntax(color("foreground")),
			"float": syntax(color("foreground")),
			"function": syntax(color("function")),
			"function.builtin": syntax(color("function")),
			"function.call": syntax(color("function")),
			"function.decorator": syntax(color("function")),
			"function.macro": syntax(color("function")),
			"function.method": syntax(color("function")),
			"function.method.call": syntax(color("function")),
			// 'function.special.definition': syntax('#FF00FF'),
			"hint": syntax(color("foreground")),
			"keyword": syntax(color("operator")),
			"keyword.conditional": syntax(color("keyword")),
			"keyword.conditional.ternary": syntax(color("keyword")),
			"keyword.coroutine": syntax(color("keyword")),
			"keyword.debug": syntax(color("keyword")),
			"keyword.directive": syntax(color("keyword")),
			"keyword.directive.define": syntax(color("keyword")),
			"keyword.exception": syntax(color("keyword")),
			"keyword.export": syntax(color("keyword")),
			"keyword.function": syntax(color("keyword")),
			"keyword.import": syntax(color("keyword")),
			"keyword.modifier": syntax(color("keyword")),
			"keyword.operator": syntax(color("keyword")),
			"keyword.repeat": syntax(color("keyword")),
			"keyword.return": syntax(color("keyword")),
			"keyword.type": syntax(color("type")),
			"label": syntax(color("foreground")),
			"link_text": syntax(color("string")),
			"link_uri": syntax(color("comment")),
			"module": syntax(color("foreground")),
			"namespace": syntax(color("interface")),
			"number": syntax(color("number")),
			"number.float": syntax(color("foreground")),
			"operator": syntax(color("operator")),
			"parameter": syntax(color("variable")),
			"parent": syntax(color("foreground")),
			"predictive": syntax(color("foreground")),
			"predoc": syntax(color("foreground")),
			"preproc": syntax(color("foreground")),
			"primary": syntax(color("primary")),
			"property": syntax(color("property")),
			"property.json_key": syntax(color("property")),
			"punctuation": syntax(color("punctuation")),
			"punctuation.bracket": syntax(color("punctuation")),
			"punctuation.delimiter": syntax(color("punctuation")),
			"punctuation.delimiter.jsx": syntax(color("punctuation")),
			"punctuation.list_marker": syntax(color("punctuation")),
			"punctuation.special": syntax(color("punctuation")),
			"punctuation.special.symbol": syntax(color("punctuation")),
			"selector": syntax(color("variable")),
			"selector.pseudo": syntax(color("function")),
			"string": syntax(color("string")),
			"string.doc": syntax(color("string")),
			"string.documentation": syntax(color("string")),
			"string.escape": syntax(color("class")),
			"punctuation.markup": syntax(color("punctuation")),
			"string.regex": syntax(color("regex")),
			"string.regexp": syntax(color("regex")),
			"string.special": syntax(color("string")),
			"string.special.path": syntax(color("string")),
			"string.special.symbol": syntax(color("string")),
			"string.special.url": syntax(color("string")),
			"symbol": syntax(color("string")),
			"tag": syntax(color("keyword")),
			"tag.attribute": syntax(color("keyword")),
			"tag.delimiter": syntax(color("keyword")),
			"tag.doctype": syntax(color("keyword")),
			"text": syntax(color("foreground")),
			"text.literal": syntax(color("secondaryForeground")),
			"title": syntax(color("primary"), "bold"),
			"type": syntax(color("interface")),
			"type.builtin": syntax(color("type")),
			"type.builtin.class": syntax(color("class")),
			"type.class.definition": syntax(color("type")),
			"type.definition": syntax(color("type")),
			"type.interface": syntax(color("type")),
			"type.super": syntax(color("type")),
			"variable": syntax(color("variable")),
			"variable.builtin": syntax(color("variable")),
			"variable.member": syntax(color("variable")),
			"variable.parameter": syntax(color("variable")),
			"variable.special": syntax(color("constant")),
			"variant": syntax(color("variable")),
		},
	};
};

function colorGetter(isDark: boolean, palette: Palette) {
	return (key: string, style?: "semi-transparent"): string => {
		const color = palette[key];
		const opacity = style === "semi-transparent" ? "4D" : "";
		if (typeof color === "string") {
			return color + opacity;
		}
		return color[isDark ? 0 : 1] + opacity;
	};
}

function syntax(color: string, ...styles: ("bold" | "italic")[]): HighlightStyleContent {
	return {
		color,
		font_style: styles.includes("italic") ? "italic" : null,
		font_weight: styles.includes("bold") ? 700 : null,
	};
}
